[package]
name = "pulse_auction"
version.workspace = true
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin = "2.0.0"
pulse_adapter = { path = "../pulse_adapter" }

[dev-dependencies]
snforge_std = "0.52.0"
assert_macros = "2.11.2"
cairo_test = "2.12.0"

[[target.starknet-contract]]
sierra = true
casm = true

[[target.lib]]

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
